export const colors = {
	COLOR_PRIMARY: "#0072FF",
	COLOR_LIGHT: "#fff",
	COLOR_DARK: "#000",
	COLOR_DARK_ALT: "#262626",
};


export const categories = [
	{
		category: "Alles",
	},
	{
		id: "01",
		category: "Dieren",
	},
	{
		id: "02",
		category: "Bloemen",
	},
	{
		id: "03",
		category: "Steden",
	},
];

export const productList = [
	{
		category: "Dieren",
		name: "Chic'n Chic",
		image: require("../assets/images/image1.webp"),
		price: "€49,95",
		rating: "4.5",
		description: "Deze reiskoffer heeft een vrolijk ontwerp met kippen. Perfect voor de reiziger met een knipoog naar het platteland!",
	},
	{
		category: "Steden",
		name: "London Calling",
		image: require("../assets/images/image2.webp"),
		price: "€69,95",
		rating: "4.2",
		description: "Een stijlvolle koffer met een iconisch Londen-thema, inclusief de beroemde bezienswaardigheden van de stad.",
	},
	{
		category: "Dieren",
		name: "Dolphin Dive",
		image: require("../assets/images/image3.webp"),
		price: "€54,95",
		rating: "4.2",
		description: "Duik in je volgende avontuur met deze koffer die versierd is met speelse dolfijnen, ideaal voor liefhebbers van de zee.",
	},
	{
		category: "Dieren",
		name: "Bear Necessities",
		image: require("../assets/images/image4.webp"),
		price: "€64,95",
		rating: "4.2",
		description: "Deze koffer toont een schattige beer in de natuur, perfect voor de avontuurlijke reiziger die van het buitenleven houdt.",
	},
	{
		category: "Dieren",
		name: "Lazy Traveler",
		image: require("../assets/images/image5.webp"),
		price: "€59,95",
		rating: "4.2",
		description: "Ontspan met deze koffer die een luiaard toont. Voor degenen die hun reis op een rustig tempo willen beleven.",
	},
	{
		category: "Dieren",
		name: "Moo-velous Journey",
		image: require("../assets/images/image6.webp"),
		price: "€62,95",
		rating: "4.2",
		description: "Een speelse koffer met een koeienmotief, voor de reiziger die houdt van een beetje boerderijflair.",
	},
	{
		category: "Dieren",
		name: "Galloping Globetrotter",
		image: require("../assets/images/image7.webp"),
		price: "€67,95",
		rating: "4.2",
		description: "Ga op avontuur met deze koffer, versierd met een galopperend paard, ideaal voor paardenliefhebbers.",
	},
	{
		category: "Bloemen",
		name: "Floral Getaway",
		image: require("../assets/images/image8.webp"),
		price: "€57,95",
		rating: "4.2",
		description: "Deze koffer met een bloemenprint brengt een vleugje natuur en kleur naar elke reis.",
	},
	{
		category: "Dieren",
		name: "Koala Komfort",
		image: require("../assets/images/image9.webp"),
		price: "€61,95",
		rating: "4.2",
		description: "Een knusse koffer met een koala-ontwerp, voor de reiziger die houdt van schattige dieren en comfort.",
	},
	{
		category: "Dieren",
		name: "Hare's Hideaway",
		image: require("../assets/images/image10.webp"),
		price: "€55,95",
		rating: "4.2",
		description: "Deze koffer heeft een charmant haasontwerp, perfect voor een lente- of natuurthema.",
	},
	{
		category: "Dieren",
		name: "Feathered Flight",
		image: require("../assets/images/image11.webp"),
		price: "€53,95",
		rating: "4.2",
		description: "Een elegante koffer met een vogelontwerp, ideaal voor vogelliefhebbers en natuurliefhebbers.",
	},
	{
		category: "Dieren",
		name: "Bambi's Adventure",
		image: require("../assets/images/image12.webp"),
		price: "€66,95",
		rating: "4.2",
		description: "Geniet van de natuur met deze koffer, versierd met een schattige afbeelding van Bambi in het bos.",
	},
	{
		category: "Dieren",
		name: "Butterfly Bliss",
		image: require("../assets/images/image13.webp"),
		price: "€58,95",
		rating: "4.2",
		description: "Deze koffer toont prachtige vlinders en brengt een vleugje gratie en kleur naar je reis.",
	},
	{
		category: "Steden",
		name: "Paris Passport",
		image: require("../assets/images/image14.webp"),
		price: "€72,95",
		rating: "4.2",
		description: "Een elegante koffer met een Parijs-thema, perfect voor de stijlvolle reiziger die houdt van de Franse cultuur.",
	},
	{
		category: "Bloemen",
		name: "Tropical Escape",
		image: require("../assets/images/image15.webp"),
		price: "€65,95",
		rating: "4.2",
		description: "Deze koffer met tropische bloemen zorgt voor een exotisch gevoel bij elke reis.",
	},
];
